#!/usr/bin/env python3
"""
parse_draft_semantic.py
=======================

Semantic draft ingestion pipeline:
- parses bibliography from TEI into BibTeX (reuses parse_references.py);
- extracts citation mentions and fact markers from draft and parts;
- exports machine-friendly maps for downstream tooling.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Set

from parse_references import (
    NS,
    generate_bibtex_entry,
    parse_tei_references,
)
import xml.etree.ElementTree as ET


@dataclass
class CitationOccurrence:
    """Stores citation location metadata."""

    file: str
    line: int
    raw: str
    keys: List[str]


@dataclass
class FactOccurrence:
    """Stores evidence marker location metadata."""

    file: str
    line: int
    code: str
    raw: str


def _extract_citation_occurrences(path: Path) -> List[CitationOccurrence]:
    pattern = re.compile(r"\\(?:cite|citep|citet)\{([^}]+)\}")
    occurrences: List[CitationOccurrence] = []
    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()

    for line_num, line in enumerate(lines, start=1):
        for match in pattern.finditer(line):
            keys = [k.strip() for k in match.group(1).split(",") if k.strip()]
            occurrences.append(
                CitationOccurrence(
                    file=str(path),
                    line=line_num,
                    raw=match.group(0),
                    keys=keys,
                )
            )
    return occurrences


def _extract_fact_occurrences(path: Path) -> List[FactOccurrence]:
    pattern = re.compile(r"\[(E-[A-Z0-9]+)\]")
    occurrences: List[FactOccurrence] = []
    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()

    for line_num, line in enumerate(lines, start=1):
        for code in pattern.findall(line):
            occurrences.append(
                FactOccurrence(file=str(path), line=line_num, code=code, raw=line.strip())
            )
    return occurrences


def _build_bibtex_from_tei(tei_path: Path, output_bib_path: Path) -> Dict[str, str]:
    try:
        refs_by_xml_id = parse_tei_references(str(tei_path))
        tree = ET.parse(str(tei_path))
        root = tree.getroot()
    except Exception as exc:
        # Keep previously curated bibliography if TEI is malformed.
        if output_bib_path.exists() and output_bib_path.stat().st_size > 0:
            print(f"Warning: TEI parse failed ({exc}); keep existing BibTeX: {output_bib_path}")
            return {}
        raise
    ordered_refs = []
    for bibl in root.findall(".//tei:listBibl/tei:biblStruct", NS):
        xml_id = bibl.get("{http://www.w3.org/XML/1998/namespace}id", "")
        if xml_id:
            ordered_refs.append(xml_id)

    citation_to_xml: Dict[str, str] = {}
    for idx, xml_id in enumerate(ordered_refs, start=1):
        citation_to_xml[str(idx)] = xml_id

    output_bib_path.parent.mkdir(parents=True, exist_ok=True)
    with output_bib_path.open("w", encoding="utf-8") as bib:
        bib.write("% Auto-generated by parse_draft_semantic.py\n")
        bib.write(f"% Source: {tei_path}\n")
        bib.write(f"% Entries discovered: {len(ordered_refs)}\n\n")

        for cite_num, xml_id in citation_to_xml.items():
            ref = refs_by_xml_id.get(xml_id)
            if not ref:
                continue
            bib.write(generate_bibtex_entry(ref, int(cite_num)))
            bib.write("\n\n")

    return citation_to_xml


def run_pipeline(
    project_root: Path,
    tei_rel: str,
    draft_rel: str,
    parts_rel: str,
    bib_rel: str,
    output_dir_rel: str,
) -> None:
    tei_path = project_root / tei_rel
    draft_path = project_root / draft_rel
    parts_dir = project_root / parts_rel
    bib_path = project_root / bib_rel
    output_dir = project_root / output_dir_rel
    output_dir.mkdir(parents=True, exist_ok=True)

    citation_to_xml = _build_bibtex_from_tei(tei_path, bib_path)

    citation_occurrences: List[CitationOccurrence] = []
    fact_occurrences: List[FactOccurrence] = []
    scanned_files: Set[Path] = set()

    if draft_path.exists():
        scanned_files.add(draft_path)
    scanned_files.update(parts_dir.glob("*.tex"))

    for file_path in sorted(scanned_files):
        citation_occurrences.extend(_extract_citation_occurrences(file_path))
        fact_occurrences.extend(_extract_fact_occurrences(file_path))

    used_cite_keys = sorted(
        {
            key
            for occurrence in citation_occurrences
            for key in occurrence.keys
            if key.strip()
        }
    )

    citations_map = {
        "citation_to_tei_xml_id": citation_to_xml,
        "used_citation_keys_in_text": used_cite_keys,
        "occurrences": [asdict(item) for item in citation_occurrences],
    }

    evidence_map = {
        "fact_codes_detected": sorted({item.code for item in fact_occurrences}),
        "occurrences": [asdict(item) for item in fact_occurrences],
    }

    summary = {
        "tei_path": str(tei_path),
        "draft_path": str(draft_path),
        "parts_path": str(parts_dir),
        "bib_output": str(bib_path),
        "total_citation_occurrences": len(citation_occurrences),
        "total_fact_occurrences": len(fact_occurrences),
        "unique_used_citations": len(used_cite_keys),
        "unique_fact_codes": len(evidence_map["fact_codes_detected"]),
    }

    (output_dir / "citations_map.json").write_text(
        json.dumps(citations_map, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (output_dir / "evidence_map.json").write_text(
        json.dumps(evidence_map, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (output_dir / "semantic_summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    print("Semantic parse complete.")
    print(f"- BibTeX written: {bib_path}")
    print(f"- Citations map: {output_dir / 'citations_map.json'}")
    print(f"- Evidence map: {output_dir / 'evidence_map.json'}")
    print(f"- Summary: {output_dir / 'semantic_summary.json'}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Parse draft semantically and export maps.")
    parser.add_argument("--tei", default="src/paper_data/new_draft.tei")
    parser.add_argument("--draft", default="src/paper_data/new_draft.md")
    parser.add_argument("--parts", default="parts")
    parser.add_argument("--bib-output", default="refs/bib/references.bib")
    parser.add_argument("--output-dir", default="out/semantic")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parent.parent
    run_pipeline(
        project_root=project_root,
        tei_rel=args.tei,
        draft_rel=args.draft,
        parts_rel=args.parts,
        bib_rel=args.bib_output,
        output_dir_rel=args.output_dir,
    )


if __name__ == "__main__":
    main()
